#!/usr/bin/env bash
# Open or update the release pull request, the way jdx/mise-action does it,
# with the version kept in ./VERSION instead of package.json: this action has
# no JavaScript and no reason to carry node just to hold a version number.
#
# Merging that pull request is what releases: release.yml tags the merge
# commit with the version in ./VERSION.
set -euo pipefail

cur_version="$(tr -d '[:space:]' <VERSION)"
[[ "$cur_version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || {
  echo "VERSION holds '$cur_version', not X.Y.Z" >&2
  exit 1
}

latest_tag="$(git tag --list 'v*' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -1 || true)"

# A version that is ahead of the latest tag is a release PR that has merged
# and not yet been tagged, which release.yml is about to do.
# Before the first release VERSION is 0.0.0, which is never tagged.
if [ -n "$latest_tag" ] && [ "v$cur_version" != "$latest_tag" ]; then
  echo "VERSION $cur_version is not tagged yet (latest is $latest_tag); release.yml tags it"
  exit 0
fi
if [ -z "$latest_tag" ] && [ "$cur_version" != 0.0.0 ]; then
  echo "VERSION $cur_version is not tagged yet (no release exists); release.yml tags it"
  exit 0
fi

if [ -n "$latest_tag" ]; then
  commits_since_release="$(git rev-list "$latest_tag"..HEAD --count)"
  if [ "$commits_since_release" -eq 0 ]; then
    echo "No commits since $latest_tag"
    exit 0
  fi
  echo "Found $commits_since_release commits since $latest_tag"
fi

# With no tag at all, git-cliff answers with its initial_tag (v0.1.0).
version="$(git cliff --bumped-version)"
if [ "$version" = "$latest_tag" ] || [ "${version#v}" = "$cur_version" ]; then
  echo "No version bump from the commits since ${latest_tag:-the start}; nothing to release"
  exit 0
fi

changelog="$(git cliff --bump --unreleased | tail -n +2)"

if [ "${DRY_RUN:-1}" = 1 ]; then
  echo "version: $version"
  echo "changelog: $changelog"
  exit 0
fi

if [ -z "$changelog" ] || [ "$changelog" = "<!-- generated by git-cliff -->" ]; then
  echo "No unreleased changes found"
  exit 0
fi

git config user.name mise-en-dev
git config user.email 123107610+mise-en-dev@users.noreply.github.com

# The checkout uses persist-credentials: false, so plain git push needs gh's
# credential helper to authenticate with GITHUB_TOKEN.
gh auth setup-git

echo "${version#v}" >VERSION
git add VERSION
git checkout -B release
git commit -m "chore: release $version"
git push origin release --force

# release.yml acts only on a merged PR carrying this label. Idempotent, so a
# new repository gets it and an existing one is unchanged.
gh label create release --force --color 0E8A16 --description "Release pull request opened by release-plz"

# Decide between create and edit by asking, rather than by whether create
# failed: create also fails for reasons that have nothing to do with an
# existing PR, and editing then would hide them.
existing_pr="$(gh pr list --head release --base main --state open --json number --jq '.[0].number // empty')"
if [ -n "$existing_pr" ]; then
  gh pr edit "$existing_pr" --title "chore: release $version" --body "$changelog" --add-label release
  echo "Updated release PR #$existing_pr"
else
  gh pr create --head release --base main --title "chore: release $version" --body "$changelog" --label release
  echo "Created the release PR"
fi
